#ifndef _TERMINAL_JSON_CONSTANTS_H
#define _TERMINAL_JSON_CONSTANTS_H

#define JSON_CARD_TYPE_NAME "cardType"
#define JSON_TRANSACTION_TYPE_NAME "TransactionType"

#define JSON_TRANSACTION_TYPE_CHEQUE "Cheque"
#define JSON_TRANSACTION_TYPE_SAVINGS "Savings"
#define JSON_TRANSACTION_TYPE_CREDIT "Credit"

#endif
